# Generated by Django 3.1.4 on 2021-01-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210118_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetails',
            name='posted_on',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
