# Generated by Django 3.1.4 on 2021-02-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_workdetails_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetails',
            name='jobdes',
            field=models.FileField(blank=True, upload_to='job/'),
        ),
    ]
