# Generated by Django 3.1.4 on 2021-02-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workdetails_jobdes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdetails',
            name='jobdes',
        ),
    ]
