# Generated by Django 3.1.4 on 2021-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210225_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetails',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
