# Generated by Django 3.1.4 on 2021-03-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_workdetails_verify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workdetails',
            options={'verbose_name': 'My image'},
        ),
    ]
